aoi:
  west: 72.77
  south: 18.89
  east: 72.99
  north: 19.27

grid:
  cell_size_deg: 0.01

time_window:
  start: "2023-03-01"
  end: "2023-05-31"

gee:
  sentinel2_collection: "COPERNICUS/S2_HARMONIZED"
  landsat8_collection: "LANDSAT/LC08/C02/T1_L2"
  landsat9_collection: "LANDSAT/LC09/C02/T1_L2"
  srtm_collection: "USGS/SRTMGL1_003"

output_paths:
  grid: "data/grid.geojson"
  master_data: "data/cells_master.geojson"
